baseURL = "https://lukibelleauthor.com/"
languageCode = "en-us"
title = "Luki Belle – Fiction Author"

enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true